import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  modal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#00000080",
  },
  modalBtnClose: {
    backgroundColor: "#FFDA1F",
    flexDirection: "row",
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    justifyContent: "space-between",
    alignItems: "center",
    width: "75%",
  },
  modalBtnCloseHeader: {
    fontWeight: "bold",
    fontSize: 18,
    marginLeft: 10,
  },
  modalBtn: {
    backgroundColor: "#FFDA1F",
    paddingVertical: 7,
    paddingHorizontal: 25,
    marginTop: 5,
    borderRadius: 5,
  },
  modalBtnTxt: {
    fontWeight: "bold",
    fontSize: 16,
  },
  charts: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  chartsTitle: {
    fontSize: 16,
    borderRadius: 500,
    paddingHorizontal: 10,
    marginVertical: 10,
    fontWeight: "bold",
    color: "#FFF",
    backgroundColor: "#5Cb0FF",
    textShadowColor: "rgba(0, 0, 0, 0.50)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 0 },
  },
  chartsPedingTasks: {
    flex: 1,
    marginLeft: 30,
    marginBottom: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  tasksGrid: {
    flex: 2,
    padding: 10,
    flexDirection: "row",
  },
  tasks: {
    flex: 1,
    height: "100%",
    marginLeft: 5,
  },
  grid: {
    flex: 1,
    height: "100%",
    marginRight: 5,
  },
  
  /* Listas: */
  header: {
    textAlign: "center",
    backgroundColor: "#FFDA1F",
    paddingVertical: 1,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    fontWeight: "bold",
  },
  item: {
    flex: 1,
    height: 80,
    paddingVertical: 5,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  colorMatter: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderRightWidth: 30,
    borderTopWidth: 30,
    borderRightColor: "transparent",
    borderTopColor: "red",
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 1,
  },
  colorMatterBorder: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderRightWidth: 31,
    borderTopWidth: 31,
    borderRightColor: "transparent",
    borderTopColor: "#ffffff80",
    position: "absolute",
    left: 0,
    top: 0,
  },
  dateTask: {
    fontSize: 11,
    color: "#fff",
    position: "absolute",
    top: 3,
    left: 3,
  },
  title: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 15,
    textShadowColor: "rgba(0, 0, 0, 0.50)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 0 },
  },
  info: {
    fontSize: 13,
    color: "#fff",
  },
  infoTask: {
    fontSize: 13,
    marginRight: 3,
    color: "#fff",
  },
  infoIcon: {
    flexDirection: "row",
    alignItems: "center",
  },
  matterIcon: {
    textShadowColor: "#00000030",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  priorityIndicator: {
    position: "absolute",
    bottom: 3,
    right: 3,
    alignItems: "center",
    flexDirection: "row",
  },
  priorityIndicatorTxt: {
    fontSize: 14,
    color: "#ffffffAA",
  },
  emptyList: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#00000011",
    height: 55,
  },
  emptyListTxt: {
    fontSize: 16,
    color: "#00000077",
  },
  viewAll: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFDA1F",
    paddingHorizontal: 25,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    height: 35,
  },
  viewAllTxt: {
    fontWeight: "bold",
  },
});

export default styles;
