import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
  },
  cells: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "#F5C000",
    borderRadius: 5,
    paddingVertical: 3,
    paddingHorizontal: 5,
  },
  priority: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#fff",
    textShadowColor: "rgba(0, 0, 0, 0.40)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 0 },
  },
  frequencyTxt: {
    marginLeft: 10,
  },
  addOneBtn: {
    marginRight: 2,
    marginLeft: 3,
  },
  addRemoveBtn: {
    marginVertical: 3,
    borderRadius: 3,
    backgroundColor: "#FFDA1F",
  },
  textInput: {
    borderRadius: 3,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 2,
    flexDirection: "row",
  },
  input: {
    textAlign: "center",
    borderBottomColor: "#000",
    borderBottomWidth: 1,
  },
  days: {
    marginRight: 15,
  },
  textInfo: {
    color: "#00000080",
    marginTop: 5,
    marginBottom: 3,
    fontSize: 9.3,
    lineHeight: 9.5,
    textAlign: "justify",
  },
  timeAndEdit: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 70,
    marginVertical: 5,
  },
  time: {
    flex: 2,
  },
  calendar: {
    borderRadius: 5,
    borderColor: "#5CB0FF",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5CB0FF",
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
    paddingHorizontal: 3,
    height: "100%",
  },
  calendarBtn: {
    justifyContent: "center",
    backgroundColor: "#fff",
    borderColor: "#5CB0FF",
    borderRadius: 5,
    borderWidth: 2,
    alignItems: "center",
    width: "100%",
  },
  calendarTxt: {
    fontWeight: "bold",
    color: "#5CB0FF",
    letterSpacing: 3,
    fontSize: 22,
    textShadowColor: "rgba(0, 0, 0, 0.20)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 0 },
  },
  editBtn: {
    flex: 1,
    borderColor: "#5CB0FF",
    borderRadius: 5,
    marginLeft: 5,
    borderWidth: 3,
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
  },
  txtBtnSave: {
    fontWeight: "bold",
    fontSize: 20,
    letterSpacing: 1,
    color: "#5CB0FF",
  },

  /* Botões negativos: */
  negativesBtns: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    height: 150,
  },
  mostNegativesBtns: {
    flex: 2,
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  negativeBtn: {
    borderWidth: 2,
    borderColor: "#F00",
    flex: 1,
    flexDirection: "row",
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  negativeIcon: {
    borderColor: "#F00",
    flex: 1,
    flexDirection: "row",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  negativeTxt: {
    textAlign: "center",
    borderColor: "#F00",
    flex: 3,
    fontSize: 16,
    color: "#F00",
    fontWeight: "bold",
    marginRight: 25,
    flexDirection: "row",
  },
  logoutBtn: {
    flex: 1,
    marginLeft: 3,
    borderRadius: 2,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: "#F00",
    flexDirection: "row",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutTxt: {
    alignItems: "center",
    textAlign: "center",
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 16,
    width: 60,
  },
  siteBox: {
    marginTop: 10,
    alignItems: "center",
    textAlign: "center",
    flexDirection: "row",
  },
  siteTxt: {
    fontSize: 16,
    color: "#444",
    textDecorationLine: "underline",
    letterSpacing: 1,
  },
  siteIco: {
    marginTop: 3,
  },
});

export default styles;
